Merge upstream to master
krux/carbon pull request #3
Opened 2017-03-16 20:46 UTC by hanpeter

2017-03-16 20:59 UTC, paul-krohn approved these changes
👍

2017-03-20 22:05 UTC, dpricha89 approved these changes
👍

2017-03-20 22:31 UTC, dcrampton-sfdc requested changes
Please add description to the pull request covering what we covered in 1:1 on Flowdock.

2017-03-20 22:38 UTC, dcrampton-sfdc approved these changes

2017-03-20 22:39 UTC, merged